### ISSUE TITLE
Header Format

### ISSUE THREAD

**Issue by rnestler** [fontobene/fontobene#15]
The header format currently consists of several toml like sections.

Its not clear if the order is important. If the order and number of fields is not defined, we probably need some kind of separator from the header to the body.

**Comment by dbrgn** [comment]
Yep, that problem started when we introduced the header sections :)

I'd suggest to use "---" to separate the header from the body. Opinions, @rnestler @ubruhin?

**Comment by dbrgn** [comment]
Ping @rnestler @ubruhin :)

**Comment by ubruhin** [comment]
Isn't it enough to consider the first occurrence of a glyph (`[****]`) the end of the header?

**Comment by dbrgn** [comment]
No, we decided to use sections in the header too, which start with `[format]`, `[font]` or `[user]`. See https://github.com/fontobene/fontobene/blob/master/SPECIFICATION.md#header

**Comment by ubruhin** [comment]
> No, we decided to use sections in the header too

Yes, but sections with four hex digits as name (e.g. `[0041]`) can be considered as glyphs and thus automatically mark the end of the header.

EDIT: Or a slightly other definition: Every section other than `[format]`, `[font]` or `[user]` automatically marks the end of the header.

**Comment by dbrgn** [comment]
Since we *might* introduce new sections in the future, I'd definitely go with the first variant. Or with an explicit separator, might also make the file easier to read.

What is your opinion, @rnestler?

**Comment by dbrgn** [comment]
My preferred solution is to have `---` on a single line as a separator between header and body.

**Comment by dbrgn** [comment]
Actually I take it back. I think we should even hardcode the valid header sections in the grammar.

**Comment by dbrgn** [comment]
Hm, I just noticed a problem in the current spec:

> The first empty line separates the header from the body.

That is not what we discussed here. Should we use an empty line as separator, or should we stick with a wording like this?

> The body starts with the first valid glyph declaration.

Disallowing empty lines in the header might actually be the simpler solution.
