### ISSUE TITLE
Allow to remove (leading) zeros in coordinates

### ISSUE THREAD

**Issue by ubruhin** [fontobene/fontobene#21]
A glyph like this:

    [0021] !
    0,0;0,0.5
    0,3;0,9

Could be shortened by removing leading zeros from coordinates (including the number "0" itself):

    [0021] !
    ,;,.5
    ,3;,9

A short test with a *.bene file with ~2600 glyphs is ~2% smaller after applying this optimization :) But I'm not sure if the also reduced readability is worth it...

**Comment by dbrgn** [comment]
Hm, I don't think that's worth it for 2%. If we'd optimize for space, we'd probably be best off with a binary format, but I'd stick with human-readable.

@rnestler your opinion?

**Comment by ubruhin** [comment]
> If we'd optimize for space, we'd probably be best off with a binary format, but I'd stick with human-readable.

IMO we should find a good compromise between human readability and file size because probably both is important for the target audience of a stroke font. Or maybe the file size is not that important, but the time required for parsing it, which also depends on the file size.

Btw, LFF does remove leading zeros if there is a following decimal point (e.g. `.5` instead of `0.5`), but it keeps zeros not followed by a decimal point. This is actually quite common and probably most string-to-float implementations will already handle such numbers correctly, so I think we should at least allow this kind of optimization...

**Comment by dbrgn** [comment]
> Or maybe the file size is not that important, but the time required for parsing it

Conditional parsing will probably slow down parsing because there are more branches. We won't know without benchmarking though.

I agree about the compromise between readability and size, but I don't think it's worth it for a 2% change in file size :)

> Btw, LFF does remove leading zeros if there is a following decimal point (e.g. .5 instead of 0.5), but it keeps zeros not followed by a decimal point.

That would be OK with me.

**Comment by dbrgn** [comment]
Updated the grammar.

Spec needs update.
