### ISSUE TITLE
Change position of bulge parameter of arc segments

### ISSUE THREAD

**Issue by ubruhin** [fontobene/fontobene#27]
Currently, the bulge parameter of an arc segment is added to its **end coordinate**:

> In addition to straight lines, polylines can contain circular arc segments. This is done by adding a third parameter, called bulge, to the coordinate pair of the end coordinate of an arc segment.

Example:

    [0066] f
    1,0;1,7.5;2.5,9,-4.5;3,9
    0,6;3,6

This means that:
- The first coordinate pair of each polyline will *never* have a bulge parameter, as it can't be the end coordinate of an arc segment.
- It's not possible to properly represent implicitly closed polylines (a polyline which has an implicit last coordinate which equals to the first coordinate) because the implicit coordinate can't have a bulge specified. So the line between the last and the first coordinate can't be an arc segment but only a straight line.

Even if we currently don't support implicitly closed polylines, maybe we add them some time in future. They could be useful for fonts specifying areas instead of strokes, so all polylines need to be closed, like this:

![auswahl_010](https://user-images.githubusercontent.com/5374821/36874289-a1169334-1dab-11e8-89e6-47dbf035b9c3.png)

So maybe it would be better to move the bulge parameter to the **start coordinate** of arc segments. The example would then look like this:

    [0066] f
    1,0;1,7.5,-4.5;2.5,9;3,9
    0,6;3,6

This way, polylines are ready to have an implicit last coordinate, while keeping the ability to provide a bulge parameter for every existing line segment (because even the first coordinate can now have a bulge parameter).

Btw: Eagle also uses this concept to represent polygons, and LibrePCB now also uses it ;)

**Comment by dbrgn** [comment]
Sounds sensible. What do you think, @rnestler?
