### ISSUE TITLE
Glyph Metadata

### ISSUE THREAD

**Issue by dbrgn** [fontobene/fontobene#3]
Should we allow metadata for the glyphs? That would allow for things like kerning to be specified and give us some more flexibility in the future.

Since a polyline starts with a digit or with 0, and a reference starts with a capital C, we could simply allow lowercase key-value pairs for metadata anywhere in the glyph definition (but with the convention to put it immediately after the declaration).

```
[0041] A
foo = bar
0.8333,2.5;5.1666,2.5
0,0;3,9;6,0
```

Note that I don't currently know a concrete use case for this, it would just be here to make the format more future-proof. We *could* put kerning info here somehow though.

**Comment by ubruhin** [comment]
Nice idea, maybe we can use this some time :+1:

**Comment by dbrgn** [comment]
Do we want to tackle this in v1? If we add key-value-pairs later on, old parsers will be incompatible with v2 fonts.

I'm not sure if we really need this though. For example for kerning, a separate kerning table would be better anyways.

CC @ubruhin

**Comment by ubruhin** [comment]
> Do we want to tackle this in v1?

No, I would not add it until we have an important, concrete use-case for it.

**Comment by dbrgn** [comment]
Ok, let's close the issue.
