### ISSUE TITLE
Provide fonts which can be used by other projects

### ISSUE THREAD

**Issue by ubruhin** [fontobene/fontobene#31]
Currently we provide only the specifications, but no "real" fonts. I think it would be very useful for other people or projects if we provided some complete font files which just work. As an example: LibreCAD has a lof of LFF fonts located in their repository: https://github.com/LibreCAD/LibreCAD/tree/master/librecad/support/fonts

But...
- Where should we provide such fonts?
  - In a subdirectory of this repository?
  - In a new repository (named e.g. "fontobene-fonts")? This may be useful as the repository could be directly added as a Git submodule into other repositories. Then you have a subdirectory contained all fonts, just like in the LibreCAD repository.
- What license should they have? IMHO we should provide/accept only fonts released under the Public Domain license. Every other license may make them unusable in other projects. And having differently licensed fonts in the same repository is a mess (everyone needs to check the license of every single font, and the "include repo as submodule" advantage is problematic because you also get fonts which don't match your license model).

But when only accepting Public Domain fonts, we probably can't just convert the LibreCAD fonts as they are released under different licenses. Or are the original licenses no longer valid after converting them to FontoBene? :wink:

**Comment by dbrgn** [comment]
:+1: 

> In a new repository (named e.g. "fontobene-fonts")?

I'd vote for this variant.

> What license should they have? IMHO we should provide/accept only fonts released under the Public Domain license.

I'd accept any permissively licensed license (CC-0, Public Domain, MIT, BSD, Apache, etc). After all, we have a license header :) And as long as you're allowed to do anything, asking for a mention is fine.

**Comment by ubruhin** [comment]
I created the new repo: https://github.com/fontobene/fontobene-fonts

**Comment by ubruhin** [comment]
Closing this issue as we now have the "fontobene-fonts" repository where we also track issues about this topic...
