### ISSUE TITLE
Reference character

### ISSUE THREAD

**Issue by dbrgn** [fontobene/fontobene#4]
Right now references start with a "C".

```
[00c2] Â
C0041
1.5,11.5;3,13;4.5,11.5
```

I think this is a bit subtle, we could also discuss replacing the character with something else, for example an "@". On the other hand LFF uses the "C".

Opinions?

**Comment by ubruhin** [comment]
With the idea presented in #3, my preference now goes to "@" as reference character because this way we can threat *every* (not only lowercase) non-digit character as metadata key-value pair ;)

**Comment by dbrgn** [comment]
@ it is :)
