### ISSUE TITLE
Alignment / Scaling / Spacing

### ISSUE THREAD

**Issue by dbrgn** [fontobene/fontobene#5]
As discussed in #1, how should we handle alignment and scaling?

My suggestion would be to use the scale between 0-100 for the distance between baseline and cap height:

![terminology](http://www.loveofgraphics.com/wp-content/uploads/2011/10/AnatomyofLetter.png)

The layout engine would put y=0 on the baseline and scale the fonts according to the chosen font size so that y=100 is at the cap height.

Spacing could be done in a fixed way for now, so simply get the width of the character, left-align it and add some space on the right before placing the next character. Some simple kerning support could be added later.

I'm not sure how to handle the space character though. It could be derived from the width of a specific glyph, e.g. the capital A? Not sure if this is something that is being done by font layout engines or not.

Discussion:

- [ ] Fixed scale for height?
- [ ] Spacing between characters?
- [ ] Width of the space character?

**Comment by dbrgn** [comment]
The parser should provide the information on the height of the font (height of the highest glyph).

**Comment by dbrgn** [comment]
My current suggestion:

- The baseline of a glyph aligns with `y=0`
- The cap height of a glyph aligns with `y=9`
- The descender height may be `y<0`
- The ascender height may be `y>9`
- The left side of a glyph aligns with `x=0`
- The width and height of a glyph is not constrained
- The spacing between characters is chosen by the renderer

Rationale: With this system, many coordinates can be expressed with single digits, making the file format more compact.

**Comment by dbrgn** [comment]
Would be great to get some comments by @ubruhin and @rnestler regarding that last comment.

**Comment by ubruhin** [comment]
> My current suggestion:

Full ACK. Just one note on this one:

> The spacing between characters is chosen by the renderer

Generally yes. But there may be fonts which require some more or less space between characters. The renderer can't really know that, so it would be helpful to have the suggested spacing defined in the font file. Then the renderer can decide if and how this spacing value is used.

**Comment by dbrgn** [comment]
> Generally yes. But there may be fonts which require some more or less space between characters.

I agree. That's why I'd make the spacing parameter by the font a multiplier / factor, not an absolute value.

**Comment by dbrgn** [comment]
Relevant discussion in #29.
