### ISSUE TITLE
Prevent reference loops

### ISSUE THREAD

**Issue by dbrgn** [fontobene/fontobene#7]
With our references system, if we allow forward references (references to glyphs that haven't been defined yet when parsing from top to bottom) we can easily end up with reference loops.

```
[005B] [
C005D

[005D] ]
C005B
```

I think there are two ways to deal with this:

- Mandate a loop detection system. This can be handled with a recursion limit and a stack based loop detection (put every glyph on the stack when resolving a reference and check whether a referenced glyph was already visited previously).
- Only allow referencing characters that have previously been defined (= no forward references).

The problem with forward references is that a multi-pass parser is required. First, all declarations have to be stored. Then every reference must be processed recursively.

When a recursion limit is used, we would also have to specify how many levels of recursion are valid. Otherwise we'll end up with recursive fonts that can be parsed by *some* parsers but not by others, that choose different recursion limits. (Note that this is probably not a problem in practice, but still something that we should try to avoid.)

My suggestion would be to disallow references to characters that are still unknown.

- This elegantly solves the problem of reference loops.
- It also solves the problem that there could be invalid references, but the parser cannot know whether they're invalid before processing the entire file.
- Parsing can be done with a single pass. For every reference, simply expand references *while parsing*. Once you get to the bottom of the file, the entire parse is finished and you can be sure that the file is actually valid.
- Parsers become much simpler to write, to read and to maintain. The font files are not something that will be frequently edited by hand, so I think we should optimize for ease of implementation.

Note that I don't think that reordering of characters due to this constraint (and resulting VCS noise) will be a problem. I think most composite characters in the unicode specification actually build upon previously defined characters, e.g. ê and é have higher codepoints than e. So I think in most cases the natural sorting of the keys would be conserved anyways.

A third alternative could also be to simply parse references and let the application deal with expanding them, but I don't think that's a good idea.

**Comment by rnestler** [comment]
Being able to reference other glyphs makes the format vulnerable to attacks similar to the [billion laughs attack](https://en.wikipedia.org/wiki/Billion_laughs_attack).

**Comment by dbrgn** [comment]
Yeah, but usually you don't parse random user-uploaded fonts from the internet, the way XML webservices do :)

**Comment by ubruhin** [comment]
Ok let's disallow forward references. We can still add support for forward references in a later version if required.

**Comment by dbrgn** [comment]
Great. The current draft already includes a paragraph about that.
