### ISSUE TITLE
Translate / Scale includes

### ISSUE THREAD

**Issue by dbrgn** [fontobene/fontobene#8]
Should we make it possible to translate and/or scale includes? E.g. with `C0041 offset=0.5,1.5 scale=1.2`. That would make references a bit more flexible (more reuse) but would also make parsing more complex (parsers now need to understand and transform coordinates). Also, I think it could make the font files harder to read. Maybe repetition is sometimes not that bad.

**Comment by dbrgn** [comment]
Partial duplicate of #9. As written there: I think the added complexity isn't worth it.

**Comment by ubruhin** [comment]
> I think the added complexity isn't worth it.

Also agree here ;)
